services:
  workout-tracker:
    pull_policy: build
    build:
      context: https://github.com/jda1833/workout-tracker.git#v3.6
      dockerfile: Dockerfile
      args:
        APP_VERSION: v3.6
    ports:
      - 8000:8000
    volumes:
      - /data/dockge/stacks/workout-tracker/data/programs.db:/app/app/data/programs.db
    restart: unless-stopped
networks: {}