services:
  workout-tracker:
    image: workout-tracker:latest
    build:
      context: https://github.com/jda1833/workout-tracker.git#main
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - workout_tracker_data:/app/app/data
    restart: unless-stopped

volumes:
  workout_tracker_data:
