services:
  workout-tracker:
    pull_policy: build
    build:
      context: https://github.com/jda1833/workout-tracker.git#main
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./data/programs.db:/app/app/data/programs.db
    restart: unless-stopped
